sha1.o: sha1/sha1.c sha1/sha1.h
server.o: server.c error_code.h util.h endpoint.h protocol.h darray.h \
 event.h iloop.h loop_adapters/event_iface.h loop_adapters/../config.h \
 loop_adapters/../endpoint.h loop_adapters/../event.h \
 loop_adapters/../hhmemory.h loop_adapters/../hhassert.h \
 loop_adapters/../util.h loop_adapters/../iloop.h inlist.h hhassert.h \
 hhclock.h platform.h hhlog.h hhmemory.h server.h config.h
test_darray.o: test/test_darray.c test/../darray.h test/../util.h
test_protocol.o: test/test_protocol.c test/../protocol.h test/../darray.h \
 test/../util.h test/../util.h
test_event.o: test/test_event.c test/../event.h test/../util.h \
 test/../util.h
test_util.o: test/test_util.c test/../util.h
test_pqueue.o: test/test_pqueue.c test/../pqueue.h test/../util.h \
 test/../util.h test/../hhmemory.h
test_client.o: test/test_client.c test/../client.h test/../config.h \
 test/../endpoint.h test/../protocol.h test/../darray.h test/../util.h \
 test/../darray.h test/../event.h test/../error_code.h test/../util.h \
 test/../hhassert.h test/../hhmemory.h test/../hhlog.h
darray.o: darray.c darray.h hhassert.h hhmemory.h util.h
event_poll.o: event_poll.c
chatserver.o: servers/chatserver.c servers/../hhassert.h \
 servers/../error_code.h servers/../util.h servers/../hhlog.h \
 servers/../hhmemory.h servers/../inlist.h servers/../server.h \
 servers/../endpoint.h servers/../protocol.h servers/../darray.h \
 servers/../iloop.h servers/../config.h servers/../util.h servers/cJSON.h
echoserver.o: servers/echoserver.c servers/../server.h \
 servers/../endpoint.h servers/../protocol.h servers/../darray.h \
 servers/../util.h servers/../iloop.h servers/../config.h \
 servers/../hhlog.h servers/../util.h servers/../hhclock.h \
 servers/../platform.h
cJSON.o: servers/cJSON.c servers/cJSON.h
pqueue.o: pqueue.c darray.h hhassert.h hhmemory.h inlist.h pqueue.h \
 util.h
protocol.o: protocol.c base64/cencode.h error_code.h util.h hhassert.h \
 hhmemory.h protocol.h darray.h sha1/sha1.h
util.o: util.c util.h
cdecode.o: base64/cdecode.c base64/cdecode.h
cencode.o: base64/cencode.c base64/cencode.h
event.o: event.c event.h util.h hhassert.h hhclock.h platform.h \
 hhmemory.h pqueue.h event_epoll.c
event_epoll.o: event_epoll.c
hhmemory.o: hhmemory.c hhmemory.h
client.o: client.c client.h config.h endpoint.h protocol.h darray.h \
 util.h hhassert.h hhlog.h
endpoint.o: endpoint.c error_code.h util.h hhassert.h hhlog.h hhmemory.h \
 protocol.h darray.h endpoint.h
hhlog.o: hhlog.c hhlog.h util.h
error_code.o: error_code.c error_code.h util.h
