event_poll.o: event_poll.c
cencode.o: base64/cencode.c base64/cencode.h
cdecode.o: base64/cdecode.c base64/cdecode.h
test_event.o: test/test_event.c test/../event.h test/../util.h
test_darray.o: test/test_darray.c test/../darray.h test/../util.h
test_network.o: test/test_network.c test/../network.h test/../darray.h \
 test/../util.h
event_epoll.o: event_epoll.c
darray.o: darray.c darray.h hhassert.h hhmemory.h util.h
hhmemory.o: hhmemory.c
network.o: network.c hhassert.h hhmemory.h network.h darray.h sha1/sha1.h \
 base64/cencode.h
sha1.o: sha1/sha1.c sha1/sha1.h
event.o: event.c event.h platform.h hhmemory.h event_epoll.c
